plugins {
    id 'com.android.application'
}

android {
    namespace 'com.comfyremote.panel'
    compileSdk 35

    defaultConfig {
        applicationId 'com.comfyremote.panel'
        minSdk 29
        targetSdk 35
        versionCode 11
        versionName '2.1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}


dependencies {
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
}
